# # version: '3.8'


services:
  db_alter_auth:
    image: postgres:alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./my-dump.sql:/docker-entrypoint-initdb.d/my-dump.sql
      - alter_auth_pgdata:/var/lib/postgresql/alter_auth_pgdata
    ports:
      - "5434:5432"
    mem_limit: 500m
    mem_reservation: 200m
    cpus: 0.50
    
  web_alter_auth:
    build:  
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/alter_authentication
      - media_alter_auth_volume:/alter_authentication/media
    ports:
      - "8001:8000"
    depends_on:
      db_alter_auth:
        condition: service_healthy
    mem_limit: 500m
    mem_reservation: 200m
    cpus: 0.50

  nginx_alter_auth:
    image: nginx:1.25.5
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web_alter_auth
    mem_limit: 500m
    mem_reservation: 200m
    cpus: 0.50

volumes:
  alter_auth_pgdata:
  media_alter_auth_volume:
