# Generated by Django 5.0.4 on 2024-11-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alter_authentication', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersecondauthenticationtestparams',
            name='cols',
        ),
        migrations.RemoveField(
            model_name='usersecondauthenticationtestparams',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='usersecondauthenticationtestparams',
            name='time_limit',
        ),
    ]
