# Generated by Django 5.0.4 on 2024-12-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alter_authentication', '0004_alter_usersecondauthenticationtestparams_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsecondfactor',
            name='passvalue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
